[tool.poetry]
name = "gha-test"
version = "0.1.0"
description = ""
authors = ["Luke Marco <luke.am89@hotmail.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
